language: node_js
node_js:
  - lts/*
before_install:
  - npm install -g codecov
install: npm ci
script:
  - npm run lint
  - npm run build
  - npm test
  - codecov --token=$CODECOV_TOKEN
  - bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r report.xml
