name: CI for walnut-chess
on: push
jobs:
  test_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: bash <(curl -Ls https://coverage.codacy.com/get.sh) download
      - run: npm install -g codecov
      - run: npm ci
      - run: npm run lint
      - run: npm run build
      - run: npm test
      - run: codecov --token=$CODECOV_TOKEN
      - run: bash <(curl -Ls https://coverage.codacy.com/get.sh)

